name: Fewcha Example Production Website

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CODENAME: fewcha
  NAMESPACE: production
  AWS_REGION: us-east-1

jobs:
  install-build-and-push-website-to-s3:
    name: Deploy Production Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache handler
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: yarn install --production --frozen-lockfile
        working-directory: packages/example

      - name: Inspect tool
        run: |
          node --version
          yarn --version
          aws --version

      - name: Build client
        working-directory: packages/example
        run: |
          yarn build

      - name: Push client to S3
        run: aws s3 sync packages/example/build/ s3://example.fewcha.app/ --acl public-read
